### PR TITLE
Sync to linguist v7.5.1

### PR DESCRIPTION
**Pull request by lafriks**

### CODE REVIEW

**Comment by lafriks** [comment]
Tests still fail, will check them

**Comment by lafriks** [comment]
Added special case for `osascript` interpreter in shebang detection if it is specified with `-l` argument

**Comment by lafriks** [comment]
Will update when dependent PR's are merged

**Comment by bzz** [comment]
@lafriks thank you for the fixes, all the PRs are merged now!

After rebasing, would you be so kind to also document a new extension-based heuristic failure on samples for `.rno` at the https://github.com/src-d/enry#divergences-from-linguist?

As soon as this is merged, I'll 🔪 a new release.

**Comment by lafriks** [comment]
Rebased, I don't think there is new failures except for already documented `samples/SQL/drop_stuff.sql`. All other tests now should succeed

**Comment by lafriks** [comment]
ooooh... I finally got what you did mean, it's about unsupported regexp. Added to docs

**Comment by lafriks** [comment]
No problem, all Your requests had valid point, I'm also for clean and traceable code ;)

**Pull request merged**
